
function AdminEntryForm({kind,onClose}:{kind:'Maintenance'|'Collections'|'Expenses'|'Bank & Cash';onClose:()=>void}){
 const[amount,setAmount]=useState(kind==='Maintenance'?'1000':'');const[house,setHouse]=useState('');const[description,setDescription]=useState('');const[mode,setMode]=useState(kind==='Bank & Cash'?'Contra (Bank → Cash)':'UPI');const[error,setError]=useState('');
 const submit=(e:FormEvent)=>{e.preventDefault();const n=Number(amount);if(!n||n<=0){setError('Enter a valid amount.');return}const id=(kind==='Expenses'?'EXP-':kind==='Maintenance'?'REC-':kind==='Bank & Cash'?'CONTRA-':'COL-')+Date.now();const items=JSON.parse(localStorage.getItem('apclrwa_admin_ledger')||'[]');const entry:any={id,kind,amount:n,house,description,mode,date:new Date().toLocaleDateString('en-IN'),status:'Posted'};if(kind==='Bank & Cash'){entry.direction=mode.includes('Bank → Cash')?'Bank → Cash':'Cash → Bank';entry.debit=entry.direction==='Bank → Cash'?'Cash':'Bank';entry.credit=entry.direction==='Bank → Cash'?'Bank':'Cash';entry.narration=description||'Contra transfer'}items.push(entry);localStorage.setItem('apclrwa_admin_ledger',JSON.stringify(items));window.dispatchEvent(new Event('apclrwa-ledger-change'));onClose()};
 return <div className="resident-modal-backdrop"><form className="resident-modal" onSubmit={submit}><div className="event-modal-head"><div><div className="eyebrow">NEW {kind.toUpperCase()} ENTRY</div><h2>{kind==='Bank & Cash'?'Bank / Cash contra entry':'Record '+kind.toLowerCase()}</h2></div><button type="button" onClick={onClose}>×</button></div><div className="resident-form-grid"><label>Amount (₹)<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} required/></label>{kind!=='Bank & Cash'&&<label>House / reference<input value={house} onChange={e=>setHouse(e.target.value)} placeholder={kind==='Maintenance'?'24':'House 24 / general'}/></label>}<label>{kind==='Expenses'?'Expense description':'Narration'}<input value={description} onChange={e=>setDescription(e.target.value)} placeholder={kind==='Bank & Cash'?'Office cash withdrawal':'Enter details'} required/></label><label>Payment mode<select value={mode} onChange={e=>setMode(e.target.value)}>{kind==='Bank & Cash'?<><option>Contra (Bank → Cash)</option><option>Contra (Cash → Bank)</option></>:kind==='Expenses'?<><option>Bank</option><option>Cash</option></>:<><option>UPI</option><option>Bank transfer</option><option>Cash</option></>}</select></label></div>{kind==='Maintenance'&&<div className="entry-help"><b>Annual maintenance:</b> ₹1,000 once per year. The resident's ₹500 initial charge is managed from Residents.</div>}{kind==='Bank & Cash'&&<div className="entry-help"><b>Contra:</b> Bank → Cash debits Cash and credits Bank. Cash → Bank reverses the entry, keeping both account balances linked.</div>}{error&&<div className="login-error">{error}</div>}<div className="event-modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Post entry</button></div></form></div>
}
function AdminFinancialTable({kind}:{kind:'Maintenance'|'Collections'|'Expenses'|'Bank & Cash'|'Reports'|'Audit Trail'}){
 const[open,setOpen]=useState(false);const[ledger,setLedger]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem('apclrwa_admin_ledger')||'[]')}catch{return[]}});
 useEffect(()=>{const sync=()=>{try{setLedger(JSON.parse(localStorage.getItem('apclrwa_admin_ledger')||'[]'))}catch{}};window.addEventListener('apclrwa-ledger-change',sync);return()=>window.removeEventListener('apclrwa-ledger-change',sync)},[]);
 const base:any[]=kind==='Maintenance'?[['24','FY 2026–27','₹ 1,000','₹ 0','₹ 1,000','Due'],['31','FY 2026–27','₹ 1,000','₹ 0','₹ 1,000','Due'],['67','FY 2026–27','₹ 1,000','₹ 1,000','₹ 0','Clear']]:kind==='Collections'?[['REC-00124','28 Sep 2026','House 24','Maintenance','₹ 1,000','UPI'],['REC-00119','02 Aug 2026','House 67','Contribution','₹ 2,000','UPI']]:kind==='Expenses'?[['EXP-00031','Garden maintenance','30 Sep 2026','Bank','₹ 4,200','Approved'],['EXP-00030','Electricity bill','27 Sep 2026','Bank','₹ 3,840','Approved']]:kind==='Bank & Cash'?[['30 Sep 2026','Bank – RWA A/c','Receipts - expenses','₹ 2,17,000','Reconciled'],['30 Sep 2026','Cash in hand','Cash receipts - expenses','₹ 18,500','Reconciled']]:kind==='Reports'?[['Maintenance collection report','FY 2026–27','Collections, outstanding & defaulters','Ready'],['Income & expenditure','FY 2026–27','Income and expenses by account','Ready'],['Cash & bank book','FY 2026–27','Ledger-based movement','Ready'],['Audit pack','FY 2025–26','Receipts, vouchers, ledger and reconciliation','Ready']]:[['06 Oct 2026 21:04','committee.admin','CREATE','Maintenance receipt REC-00124'],['06 Oct 2026 20:58','committee.admin','POST','Expense voucher EXP-00031'],['06 Oct 2026 20:42','committee.admin','RECONCILE','Bank transaction #BT-00118']];
 const custom=ledger.filter(x=>x.kind===kind).map(x=>kind==='Bank & Cash'?[x.date,x.direction,x.narration,'₹ '+x.amount.toLocaleString('en-IN'),'Posted']:kind==='Maintenance'?[x.house||'—','FY 2026–27','₹ '+x.amount.toLocaleString('en-IN'),'₹ 0','₹ '+x.amount.toLocaleString('en-IN'),'Posted']:kind==='Expenses'?[x.id,x.description,x.date,x.mode,'₹ '+x.amount.toLocaleString('en-IN'),'Posted']:[x.id,x.date,x.house||'—',x.kind,'₹ '+x.amount.toLocaleString('en-IN'),x.mode||'UPI']);
 const data=[...custom,...base];const headers=kind==='Maintenance'?['House','FY','Charge','Paid','Outstanding','Status']:kind==='Collections'?['Receipt','Date','House','Type','Amount','Mode']:kind==='Expenses'?['Voucher','Description','Date','Mode','Amount','Status']:kind==='Bank & Cash'?['Date','Entry','Narration','Amount','Status']:kind==='Reports'?['Report','FY','Coverage','Status']:['Timestamp','User','Action','Entity'];
 return <section className="admin-module-stack"><section className="admin-panel"><div className="panel-head"><div><span>{kind.toUpperCase()}</span><h3>{kind}</h3></div>{['Maintenance','Collections','Expenses','Bank & Cash'].includes(kind)?<button className="admin-primary" onClick={()=>setOpen(true)}>+ Add {kind==='Bank & Cash'?'transaction':kind.toLowerCase()}</button>:<DemoBadge/>}</div><p className="module-note">{kind==='Reports'?'Reports are generated from the ledger.':'Post entries from this console; production accounting will create balanced journal entries in SQLite.'}</p>{kind==='Collections'&&<AdminPaymentVerification/>}<div className="admin-data-table-wrap"><table className="admin-data-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} className={(v==='Clear'||v==='Reconciled'||v==='Ready'||v==='Approved'||v==='Posted')?'good-cell':(v==='Due'||v==='Pending reconciliation')?'warn-cell':''}>{v}</td>)}</tr>)}</tbody></table></div>{kind==='Reports'&&<div className="report-actions"><button>Export CSV</button><button>Export PDF</button><button className="admin-primary">Generate audit pack</button></div>}{open&&<AdminEntryForm kind={kind as 'Maintenance'|'Collections'|'Expenses'|'Bank & Cash'} onClose={()=>setOpen(false)}/>}</section></section>
}
function EventManager(){
 const[events,setEvents]=useState<EventItem[]>(()=>{try{return JSON.parse(localStorage.getItem('apclrwa_events')||'')||defaultEvents}catch{return defaultEvents}});
 const[modalOpen,setModalOpen]=useState(false);
 const[editing,setEditing]=useState<EventItem|null>(null);
 const[form,setForm]=useState<EventItem>({id:'',tag:'EVENTS',title:'',text:'',date:'',location:'APC Layout'});
 const startAdd=()=>{setEditing(null);setForm({id:crypto.randomUUID(),tag:'EVENTS',title:'',text:'',date:'',location:'APC Layout'});setModalOpen(true)};
 const startEdit=(item:EventItem)=>{setEditing(item);setForm(item);setModalOpen(true)};
 const close=()=>{setModalOpen(false);setEditing(null)};
 const save=(e:FormEvent)=>{e.preventDefault();const next=editing?events.map(x=>x.id===form.id?form:x):[...events,form];setEvents(next);localStorage.setItem('apclrwa_events',JSON.stringify(next));close()};
 const remove=(id:string)=>{const next=events.filter(x=>x.id!==id);setEvents(next);localStorage.setItem('apclrwa_events',JSON.stringify(next))};
 return <section className="admin-events-panel"><div className="panel-head"><div><span>HOMEPAGE CONTENT</span><h3>Events & announcements</h3></div><button className="admin-primary" onClick={startAdd}>+ Add event</button></div>
   <p className="module-note">Events added here appear on the public homepage under Latest Updates.</p>
   <div className="event-admin-list">{events.map(item=><div className="event-admin-row" key={item.id}><div><span>{item.tag}</span><strong>{item.title}</strong><small>{item.date} • {item.location}</small></div><div><button onClick={()=>startEdit(item)}>Edit</button><button className="danger-link" onClick={()=>remove(item.id)}>Delete</button></div></div>)}</div>
   {modalOpen&&<div className="event-modal-backdrop"><form className="event-modal" onSubmit={save}><div className="event-modal-head"><div><div className="eyebrow">{editing?'EDIT HOMEPAGE ITEM':'NEW HOMEPAGE ITEM'}</div><h2>{editing?'Edit event / announcement':'Add event / announcement'}</h2></div><button type="button" onClick={close}>×</button></div><EventForm form={form} setForm={setForm}/><div className="event-modal-actions"><button type="button" onClick={close}>Cancel</button><button className="admin-primary" type="submit">{editing?'Save changes':'Publish to homepage'}</button></div></form></div>}
 </section>
}
function EventForm({form,setForm}:{form:EventItem;setForm:(v:EventItem)=>void}){
 const update=(key:keyof EventItem,value:string)=>setForm({...form,[key]:value});
 return <div className="event-form"><label>Category<input value={form.tag} onChange={e=>update('tag',e.target.value)} placeholder="EVENTS"/></label><label>Title<input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Community event title" required/></label><label>Description<textarea value={form.text} onChange={e=>update('text',e.target.value)} placeholder="What should residents know?" required/></label><div className="event-form-grid"><label>Date / time<input value={form.date} onChange={e=>update('date',e.target.value)} placeholder="18 October 2026"/></label><label>Location<input value={form.location} onChange={e=>update('location',e.target.value)} placeholder="APC Layout"/></label></div></div>
}

function AdminDashboard({onLogout}:{onLogout:()=>void}){
 const[section,setSection]=useState('Overview');
 const[selectedFY,setSelectedFY]=useState(()=>localStorage.getItem('apclrwa_selected_fy')||'2026–27');
 const nav=['Overview','Residents','Maintenance','Collections','Expenses','Bank & Cash','Reports','Events','Audit Trail'];
 const stats=fyStats[selectedFY]||fyStats['2026–27'];
 const switchFY=(fy:string)=>{setSelectedFY(fy);localStorage.setItem('apclrwa_selected_fy',fy)};
 const renderModule=()=>{
   if(section==='Residents')return <AdminResidents/>;
   if(['Maintenance','Collections','Expenses','Bank & Cash','Reports','Audit Trail'].includes(section))return <AdminFinancialTable kind={section as 'Maintenance'|'Collections'|'Expenses'|'Bank & Cash'|'Reports'|'Audit Trail'}/>;
   if(section==='Events')return <EventManager/>;
   return null;
 };
 return <div className="admin-shell">
   <aside className="admin-sidebar"><div className="admin-brand"><Logo/><div><strong>APC LAYOUT</strong><span>Committee Portal</span></div></div><div className="admin-user"><div className="admin-avatar">CA</div><div><strong>Committee Admin</strong><span>Administrator</span></div></div><nav className="admin-nav">{nav.map(item=><button key={item} className={section===item?'active':''} onClick={()=>setSection(item)}><span className="nav-icon">{({Overview:'⌂',Residents:'♙',Maintenance:'₹',Collections:'▣',Expenses:'↘','Bank & Cash':'▤',Reports:'▥',Events:'✦','Audit Trail':'✓'} as Record<string,string>)[item]}</span>{item}</button>)}</nav><button className="admin-logout" onClick={onLogout}>↪ Sign out</button></aside>
   <main className="admin-main"><header className="admin-topbar"><button className="mobile-admin-brand" onClick={()=>setSection('Overview')}><Logo/></button><div><div className="eyebrow">APC LAYOUT • COMMITTEE PORTAL</div><h1>{section}</h1></div><div className="admin-top-actions"><ThemeToggle/><label className="fy-switch"><span>Financial year</span><select value={selectedFY} onChange={e=>switchFY(e.target.value)}>{financialYears.map(fy=><option key={fy} value={fy}>FY {fy}</option>)}</select></label><div className="admin-profile">CA</div></div></header>
   {section==='Overview'?<><div className="admin-welcome"><div><span className="welcome-kicker">GOOD AFTERNOON</span><h2>Welcome back, Committee Admin.</h2><p>Association snapshot for <strong>FY {selectedFY}</strong>.</p></div><button className="admin-primary" onClick={()=>setSection('Events')}>+ Add homepage event</button></div>
   <div className="admin-stats">{stats.map(([value,label])=><div className="admin-stat" key={label}><span>{label}</span><strong>{value}</strong><small>Demo data • FY {selectedFY}</small></div>)}</div>
   <div className="admin-grid"><section className="admin-panel"><div className="panel-head"><div><span>FINANCIAL ACTIVITY</span><h3>Recent transactions</h3></div><button onClick={()=>setSection('Reports')}>View reports →</button></div><div className="transaction-list"><div><span className="txn-icon income">↓</span><div><strong>Maintenance payment</strong><small>House 24 • Receipt #REC-00124</small></div><b className="amount-positive">+ ₹8,500</b></div><div><span className="txn-icon expense">↑</span><div><strong>Garden maintenance</strong><small>Voucher #EXP-00031 • Bank</small></div><b className="amount-negative">− ₹4,200</b></div><div><span className="txn-icon income">↓</span><div><strong>Ganesha festival donation</strong><small>House 67 • Receipt #REC-00119</small></div><b className="amount-positive">+ ₹2,000</b></div><div><span className="txn-icon expense">↑</span><div><strong>Electricity bill</strong><small>Voucher #EXP-00030 • Bank</small></div><b className="amount-negative">− ₹3,840</b></div></div></section>
   <section className="admin-panel"><div className="panel-head"><div><span>ATTENTION</span><h3>Tasks to review</h3></div></div><div className="task-list"><div><i className="task-dot red"/>12 residents have maintenance outstanding</div><div><i className="task-dot gold"/>5 bank transactions need reconciliation</div><div><i className="task-dot green"/>FY 2025–26 audit pack is ready</div><div><i className="task-dot blue"/>3 new resident records to verify</div></div></section></div>
   <section className="admin-panel quick-panel"><div className="panel-head"><div><span>QUICK ACTIONS</span><h3>Common committee tasks</h3></div></div><div className="quick-actions"><button onClick={()=>setSection('Residents')}>+ Add resident</button><button onClick={()=>setSection('Maintenance')}>₹ Record maintenance</button><button onClick={()=>setSection('Collections')}>↓ Record collection</button><button onClick={()=>setSection('Expenses')}>↗ Record expense</button><button onClick={()=>setSection('Bank & Cash')}>▣ Bank & cash</button><button onClick={()=>setSection('Events')}>✦ Add homepage event</button></div></section>
   </>:renderModule()}
   <footer className="admin-footer">APC Layout Residents Welfare Association • FY {selectedFY} • Committee access • <button onClick={onLogout}>Sign out</button></footer>
   </main>
 </div>
}

export default function App(){
 const[signedIn,setSignedIn]=useState(()=>localStorage.getItem('apclrwa_admin_session')==='true');
 const[residentSignedIn,setResidentSignedIn]=useState(()=>localStorage.getItem('apclrwa_resident_session')==='true');
 const[view,setView]=useState<View>(()=>localStorage.getItem('apclrwa_admin_session')==='true'?'admin':localStorage.getItem('apclrwa_resident_session')==='true'?'resident':'home');
 const go=(next:View)=>{setView(next);window.scrollTo(0,0)};
 const login=()=>{setSignedIn(true);setView('admin');window.scrollTo(0,0)};
 const residentLogin=(username:string)=>{localStorage.setItem('apclrwa_resident_username',username);setResidentSignedIn(true);setView('resident');window.scrollTo(0,0)};
 const logout=()=>{localStorage.removeItem('apclrwa_admin_session');setSignedIn(false);setView('home')};
 const residentLogout=()=>{localStorage.removeItem('apclrwa_resident_session');localStorage.removeItem('apclrwa_resident_username');setResidentSignedIn(false);setView('home')};
 if(signedIn&&view==='admin')return <AdminDashboard onLogout={logout}/>;
 if(residentSignedIn&&view==='resident')return <ResidentDashboard onLogout={residentLogout}/>;
 if(view==='login')return <Login onBack={()=>go('home')} onLogin={login} onResidentLogin={residentLogin}/>;
 return <Home go={go}/>;
}function AdminPaymentVerification(){
 const[items,setItems]=useState<any[]>(getPendingPayments());
 useEffect(()=>{const sync=()=>setItems(getPendingPayments());window.addEventListener('apclrwa-payments-change',sync);return()=>window.removeEventListener('apclrwa-payments-change',sync)},[]);
 const review=(id:string,status:'Approved'|'Rejected')=>{const next=getPendingPayments().map((p:any)=>p.id===id?{...p,status,reviewedAt:new Date().toISOString(),reviewedBy:'committee.admin'}:p);savePendingPayments(next);setItems(next)};
 return <div className="verification-list">{items.length===0?<div className="verification-empty">No community payments awaiting verification.</div>:items.map((p:any)=><div className="verification-item" key={p.id}><div><span>{p.type}</span><strong>{p.resident} • House {p.house}</strong><small>{p.date} • {p.amount} • {p.id}</small></div><span className={p.status==='Pending verification'?'status-pill pending':p.status==='Approved'?'status-pill paid':'status-pill rejected'}>{p.status}</span>{p.status==='Pending verification'&&<div className="verification-actions"><button onClick={()=>review(p.id,'Rejected')}>Reject</button><button className="admin-primary" onClick={()=>review(p.id,'Approved')}>Approve</button></div>}</div>)}</div>
}


function AddResidentForm({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
 const[name,setName]=useState('');const[house,setHouse]=useState('');const[email,setEmail]=useState('');const[mobile,setMobile]=useState('');const[password,setPassword]=useState('');const[paid,setPaid]=useState(false);const[error,setError]=useState('');
 const save=(e:FormEvent)=>{e.preventDefault();if(!name||!house||(!email&&!mobile)||!password){setError('Please complete all required fields.');return}const residents=getResidents();if(residents.some(r=>r.house===house)){setError('That house / flat is already registered.');return}residents.push({id:'RES-'+Date.now(),house,name,email,mobile,password,initialCharge:500,initialChargePaid:paid,createdAt:new Date().toISOString()});saveResidents(residents);onSaved();onClose()};
 return <div className="resident-modal-backdrop"><form className="resident-modal" onSubmit={save}><div className="event-modal-head"><div><div className="eyebrow">RESIDENT REGISTRATION</div><h2>Add resident</h2></div><button type="button" onClick={onClose}>×</button></div><div className="resident-form-grid"><label>Resident name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>House / Flat<input value={house} onChange={e=>setHouse(e.target.value)} placeholder="24" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="resident@example.com"/></label><label>Mobile<input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="98XXXXXXXX"/></label><label>Password<input type="text" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Temporary login password" required/></label><div className="resident-charge-option"><strong>Initial charge: ₹500</strong><small>One-time charge created with the resident account.</small><label><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> Mark as paid</label></div></div>{error&&<div className="login-error">{error}</div>}<div className="event-modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Create resident</button></div></form></div>
}
function AdminResidents(){
 const[residents,setResidents]=useState<ResidentRecord[]>(getResidents());const[open,setOpen]=useState(false);
 useEffect(()=>{const sync=()=>setResidents(getResidents());window.addEventListener('apclrwa-residents-change',sync);return()=>window.removeEventListener('apclrwa-residents-change',sync)},[]);
 const rows=[{house:'24',name:'Demo Resident',contact:'••••••••••',initialChargePaid:true},...residents].filter((r,i,a)=>a.findIndex(x=>x.house===r.house)===i);
 return <section className="admin-module-stack"><section className="admin-panel"><div className="panel-head"><div><span>RESIDENT DIRECTORY</span><h3>Residents</h3></div><button className="admin-primary" onClick={()=>setOpen(true)}>+ Add resident</button></div><p className="module-note">Create the resident login and set whether the ₹500 initial charge is already paid. If unpaid, it appears as due in the resident portal.</p><div className="resident-admin-table"><div className="resident-admin-head"><span>House</span><span>Resident</span><span>Contact</span><span>Initial ₹500</span><span>Status</span></div>{rows.map((r:any)=><div className="resident-admin-row" key={r.house}><span>{r.house}</span><span>{r.name}</span><span>{r.contact||r.email||r.mobile||'—'}</span><span className={r.initialChargePaid?'good':''}>{r.initialChargePaid?'Paid':'Due'}</span><span className="good">Active</span></div>)}</div></section>{open&&<AddResidentForm onClose={()=>setOpen(false)} onSaved={()=>setResidents(getResidents())}/>}</section>
}

